# 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- 자동차 종류가 '세단' 또는 'SUV'
-- 2022년 11월 동안 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만
-- 출력 : 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE)
-- 대여 금액을 기준으로 내림차순 , 자동차 종류를 기준으로 오름차순, 자동차 ID를 기준으로 내림차순
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30*(1-DISCOUNT_RATE/100)) FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN ( SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                WHERE DURATION_TYPE = '30일 이상') P
ON C.CAR_TYPE = P.CAR_TYPE
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE IN ('세단','SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01')
AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * 30) >= 500000 
AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * 30 < 2000000)
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

-- <핵심>
-- INNER JOIN 과 LEFT JOIN 동시 사용
-- 기간설정 : START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01'
-- 계산식 : ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * 30)