# 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- 자동차 종류가 '세단' 또는 'SUV'
-- 2022년 11월 동안 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만
-- 출력 : 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE)
-- 대여 금액을 기준으로 내림차순 , 자동차 종류를 기준으로 오름차순, 자동차 ID를 기준으로 내림차순
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30*(1-DISCOUNT_RATE/100)) FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN ( SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                WHERE DURATION_TYPE = '30일 이상') P
ON C.CAR_TYPE = P.CAR_TYPE
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE IN ('세단','SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01')
AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * 30) >= 500000 
AND ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * 30 < 2000000)
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

-- <핵심>
-- INNER JOIN 과 LEFT JOIN 동시 사용
-- 기간설정 : START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01'
-- 계산식 : ROUND(DAILY_FEE * (1 - DISCOUNT_RATE/100) * 30)


-- 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM BOOK B JOIN (SELECT *
                  FROM BOOK_SALES
                  WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01') S 
            ON B.BOOK_ID = S.BOOK_ID 
            JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

SELECT  A.AUTHOR_ID, 
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기(너무너무너무너무 어려움)
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;

SELECT MONTH(r1.START_DATE) AS Month, r1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY r1
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS subq
ON r1.CAR_ID = subq.CAR_ID
WHERE MONTH(r1.START_DATE) BETWEEN 8 AND 10
GROUP BY Month, r1.CAR_ID
ORDER BY Month, r1.CAR_ID DESC;