-- 조건에 부합하는 중고거래 상태 조회하기 (핵심 : IF문)
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE
    WHEN STATUS="SALE" THEN '판매중'
    WHEN STATUS="RESERVED" THEN '예약중'
    ELSE '거래완료' 
END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC;

-- 자동차 평균 대여 기간 구하기 (핵심: ROUND 함수, DATEDIFF 후 +1)
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1)>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- DATETIME에서 DATE로 형 변환 (핵심 : FORMAT아니고 DATE_FORMAT!!)
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME,"%Y-%m-%d") AS 날짜
FROM ANIMAL_INS

-- 중성화 여부 파악하기 (핵심 : CASE WHEN 조건 THEN 결과 ELSE 결과 END)
SELECT ANIMAL_ID, NAME, CASE
                            WHEN SEX_UPON_INTAKE like '%Neutered%' THEN 'O'
                            WHEN SEX_UPON_INTAKE like '%Spayed%' THEN 'O'
                            ELSE 'X'
                        END AS '중성화'
FROM ANIMAL_INS

-- 이름에 el이 들어가는 동물 찾기 (핵심 : LIKE '%__%')
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE ="Dog" AND NAME LIKE '%el%'
ORDER BY NAME ASC

-- 루시와 엘라 찾기 (핵심 : in 함수)
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME in ('Lucy', 'ELLA', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID ASC

-- 고양이와 개는 몇 마리 있을까 (핵심 : count함수)
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC

-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(*) CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE