-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기 (핵심 : CONCAT)
SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B, USED_GOODS_FILE F
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) AND B.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC;

-- 조건에 맞는 사용자 정보 조회하기(핵심 : CONCAT 함수 - 문자열 붙이기, 전화번호 형식 :000-0000-0000)
SELECT USER_ID,
       NICKNAME,
       CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소,
       CONCAT(SUBSTRING(TLNO from 1 for 3), '-' ,SUBSTRING(TLNO from 4 for 4), '-' ,SUBSTRING(TLNO from 8 for 4)) AS 전화번호
FROM USED_GOODS_USER U
WHERE USER_ID in (SELECT WRITER_ID 
                  FROM USED_GOODS_BOARD
                  GROUP BY WRITER_ID
                  HAVING COUNT(BOARD_ID) >= 3 )
ORDER BY USER_ID DESC

-- 조건에 맞는 사용자와 총 거래금액 조회하기 (핵심 : GROUP BY - SUM 집계함수
SELECT U.USER_ID, U.NICKNAME, B.PRI TOTAL_SALES
FROM USED_GOODS_USER U, (SELECT WRITER_ID, SUM(PRICE) PRI
                         FROM  USED_GOODS_BOARD 
                         WHERE STATUS = "DONE"
                         GROUP BY WRITER_ID
                         HAVING SUM(PRICE)>=700000) B
WHERE U.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES ASC

-- 오랜 기간 보호한 동물(2) (핵심 : LIMIT 함수)
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O, ANIMAL_INS I
WHERE O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC LIMIT 2

-- 대여 기록이 존재하는 자동차 리스트 구하기 (핵심 : MONTH함수)
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE)=10 AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE='세단')
ORDER BY CAR_ID DESC -- 날짜를 굳이 SPLIT할 필요 없고 YEAR,MONTH,DAY 함수 쓰면됨

-- 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기 (핵심 : IF문, CASE문, GROUP BY)
## CASE문
SELECT CAR_ID,
CASE
    WHEN CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') THEN '대여중'
    ELSE '대여 가능'
END AS AVILABILITY 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;
## IF문 
SELECT CAR_ID,
 IF(CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;