-- 조건에 부합하는 중고거래 댓글 조회하기 (핵심 : DATE_FORMET)
SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d')
FROM (SELECT * FROM USED_GOODS_BOARD WHERE CREATED_DATE >= "2022-10-01" AND CREATED_DATE <= "2022-10-31") B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

-- 특정 옵션이 포함된 자동차 리스트 구하기 (핵심 : LIKE '%__%')
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC

-- 자동차 대여 기록에서 장기/단기 대여 구분하기
SELECT HISTORY_ID, 
CAR_ID, 
DATE_FORMAT(START_DATE,'%Y-%m-%d') START_DATE, 
DATE_FORMAT(END_DATE,'%Y-%m-%d') END_DATE, 
CASE
    WHEN DATEDIFF(END_DATE,START_dATE) +1 >= 30  THEN '장기 대여'  -- DATEDIFF(순,서) 중요
    ELSE '단기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') = '2022-09' -- WHERE MONTH(START_DATE)=9 도 가능
ORDER BY HISTORY_ID DESC